### ISSUE TITLE
Failing to create (conda env create -f aua4gro.yml)

### ISSUE THREAD

**Issue by Eman-Medani** [luis-chemeng/aua4gro#1]
Hi Luis, I want to use the AUA4 ff for building my topology file, however, I am finding it is difficult to Create anaconda enviroment as mention in the readme section. it keeps through error. could you help with that please

**Comment by luis-chemeng** [comment]
Hi Emman-Medani,

I noticed that there were some unnecessary modules in the yml file. I have uploaded a simplified version of the file. Please try reinstalling the Anaconda environment using this updated version. If the error persists, kindly provide more details about the issue so I can assist you further.

**Comment by Eman-Medani** [comment]
it working perfectly now! thank you Luis.

**Comment by luis-chemeng** [comment]
Thank you for using the repository, and I appreciate your contribution!
